# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 01:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.BooleanField(default=False)),
                ('firstName', models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator(message='Only letters can be input', regex='[a-zA-Z]$')])),
                ('middleInitial', models.CharField(default='', max_length=1, null=True, validators=[django.core.validators.RegexValidator(message='Only letters can be input', regex='[a-zA-Z]$')])),
                ('lastName', models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator(message='Only letters can be input', regex='[a-zA-Z]$')])),
                ('gender', models.CharField(default='', max_length=10)),
                ('name', models.CharField(default='', max_length=50)),
                ('details', models.CharField(default='', max_length=500, null=True)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('email', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skillName', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
    ]
