# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelancerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='freelancerapp.ProfileInfo')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer', to='freelancerapp.ProfileInfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancerapp.Skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancerapp.ProfileInfo')),
            ],
        ),
    ]
